namespace DBsync.Contracts;

/// <summary>
/// One local folder ⇄ one network destination, together with everything the sync engine
/// needs to service it. Persisted (the settings half) in the machine-level config store and
/// projected to the tray app with the runtime half filled in.
/// </summary>
public sealed class FolderPair
{
    /// <summary>Stable identity; generated by the service when the pair is created.</summary>
    public string Id { get; set; } = Guid.NewGuid().ToString("n");

    /// <summary>Display name shown on the flyout row, e.g. "Projects".</summary>
    public string Name { get; set; } = "";

    /// <summary>Absolute local root, e.g. <c>C:\Users\dana\Projects</c>.</summary>
    public string LocalPath { get; set; } = "";

    /// <summary>UNC or mapped-drive root, e.g. <c>\\NAS-01\team\projects</c>.</summary>
    public string SharePath { get; set; } = "";

    public DestinationKind DestKind { get; set; } = DestinationKind.Unc;

    public SyncDirection Direction { get; set; } = SyncDirection.TwoWay;

    /// <summary>When false the pair is reconciled only on the periodic sweep.</summary>
    public bool Watcher { get; set; } = true;

    /// <summary>Glob-ish patterns; a trailing slash matches a directory anywhere in the tree.</summary>
    public List<string> Excludes { get; set; } = new();

    /// <summary>Outbound throttle in bytes per second. Null or 0 means unthrottled.</summary>
    public long? UploadLimitBytesPerSecond { get; set; }

    /// <summary>How many superseded copies to retain under the pair's version store. 0 disables versioning.</summary>
    public int VersionsKept { get; set; } = 5;

    /// <summary>Copy locked files through a volume shadow copy instead of logging them as skipped.</summary>
    public bool UseVss { get; set; }

    /// <summary>True when UNC credentials for this pair live in Windows Credential Manager.</summary>
    public bool SaveCredentials { get; set; }

    /// <summary>Per-pair pause, independent of the global pause.</summary>
    public bool Enabled { get; set; } = true;

    // ---- Runtime projection. Never persisted to config.json; recomputed by the engine. ----

    public PairStatus Status { get; set; } = PairStatus.InSync;

    /// <summary>0–100 while <see cref="Status"/> is <see cref="PairStatus.Syncing"/>.</summary>
    public int Percent { get; set; }

    /// <summary>Second line of the flyout row, e.g. "Up to date · checked 2 minutes ago".</summary>
    public string Detail { get; set; } = "";

    /// <summary>Unresolved conflicts parked for this pair.</summary>
    public int PendingConflicts { get; set; }

    /// <summary>Returns a copy carrying only the persisted settings.</summary>
    public FolderPair CloneSettings() => new()
    {
        Id = Id,
        Name = Name,
        LocalPath = LocalPath,
        SharePath = SharePath,
        DestKind = DestKind,
        Direction = Direction,
        Watcher = Watcher,
        Excludes = new List<string>(Excludes),
        UploadLimitBytesPerSecond = UploadLimitBytesPerSecond,
        VersionsKept = VersionsKept,
        UseVss = UseVss,
        SaveCredentials = SaveCredentials,
        Enabled = Enabled,
    };
}
